1 MM+ records...
* NCA - 06
* SCA - 10
* FL  - 01
* TX  - 11
* MA  - 01
* IL  - 03
* CO  - 08

In [2]:
library(tidyverse)

Loading tidyverse: ggplot2
Loading tidyverse: tibble
Loading tidyverse: tidyr
Loading tidyverse: readr
Loading tidyverse: purrr
Loading tidyverse: dplyr
Conflicts with tidy packages ---------------------------------------------------
filter(): dplyr, stats
lag():    dplyr, stats

In [3]:
wfm_all = read_tsv('data/wholefoods/wfm_final.tsv', col_types="cccccccDddddcccc")
head(wfm_all,1)
#summary(wfm_all)

  Region   CustNum Store            Address
1 Mid-West 10303   Town and Country 1160 Town and Country Crossin
  City             StateAbr zip   Date       Sales SalesLy Units UnitsLy
1 Town and Country MO       63017 2016-01-04 0     19.96   0     4
  Brand          Category UPC        Description
1 Bob's Red Mill Mixes    3997800464 Mix Brownie Gf (21oz)

In [4]:
wfm_stores_by_state = wfm_all %>%     
    group_by(StateAbr) %>%
    distinct(CustNum) %>%
    select(-CustNum) %>%
    summarize(count=n()) %>%
    arrange(-count) 
wfm_stores_by_state

   StateAbr count
1  NCA      45
2  SCA      41
3  TX       37
4  MA       34
5  FL       28
6  IL       28
7  CO       21
8  NY       17
9  NJ       16
10 PA       13
11 VA       13
12 NC       12
13 AZ       11
14 OR       11
15 GA       10
16 WA       10
17 MD        9
18 OH        9
19 LA        7
20 MI        7
21 MN        7
22 CT        6
23 TN        6
24 NV        5
25 UT        5
26 AL        4
27 DC        4
28 IN        4
29 KS        4
30 NM        4
31 SC        4
32 AR        3
33 HI        3
34 MO        3
35 OK        3
36 RI        3
37 WI        3
38 KY        2
39 NE        2
40 NH        2
41 IA        1
42 ID        1
43 ME        1
44 MS        1
45 U/A       1